name: PlatformIO build
on:
  push:
    branches:
      - master
      - develop
      - fix/build

jobs:
  main:
    name: PlatformIO build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build
        run: |
          wget https://developer.nordicsemi.com/.pc-tools/nrfutil/x64-linux/nrfutil
          chmod +x nrfutil
          platformio run
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: ./out
